version: '3.8'

services:

  service-a:
    build: ./service-a
    ports:
      - "3000:3000" 
  # O consumidor
  service-b:
    build: ./service-b
    ports:
      - "5000:5000" 
    depends_on:
      - service-a  