version: '3.8'

services:

  users-service:
    build: ./users
    expose:
      - "5001" 


  orders-service:
    build: ./orders
    expose:
      - "5002"  

 
  gateway:
    build: ./gateway
    ports:
      - "8080:8080" 
    depends_on:
      - users-service
      - orders-service